#!/usr/bin/env bash
set -euo pipefail

command -v brew >/dev/null 2>&1 || { echo "Please install Homebrew before continuing: https://brew.sh/"; exit 1; }

echo "Installing tools via Homebrew to generate locally-trusted certs"
if brew ls --versions mkcert > /dev/null; then
  brew upgrade mkcert
else
  brew install mkcert
fi

if brew ls --versions nss > /dev/null; then
  brew upgrade nss
else
  brew install nss
fi

echo "Installing mkcert CA to root store"
mkcert -install

echo "Generating cert for common local domains"
mkcert localhost

echo "Moving certificates into place for Local Development"
mkdir -p certs
mv "localhost.pem" certs/localhost.pem
mv "localhost-key.pem" certs/localhost-key.pem